(when (boundp 'latex-mode-abbrev-table)
  (clear-abbrev-table latex-mode-abbrev-table))




(define-abbrev-table 'latex-mode-abbrev-table
  '(
    ("artl" "\\mapsto" nil 0)
    ("balg" "\\begin{Algorithm} " nil 0)
    ("bcase" "\\begin{Case} " nil 0)
    ("bclm" "\\begin{Claim} " nil 0)
    ("bcm" "\\begin{comment}" nil 0)
    ("bcmnt" "\\begin{comment}" nil 0)
    ("bcnd" "\\begin{Condition} " nil 0)
    ("bcnj" "\\begin{Conjecture} " nil 0)
    ("bcom" "\\begin{comment}" nil 1)
    ("bcor" "\\begin{Corollary} " nil 0)
    ("bcrit" "\\begin{Criterion} " nil 0)
    ("bctr" "\\begin{center}" nil 0)
    ("bdfn" "\\begin{Definition} " nil 0)
    ("bdef" "\\begin{Definition} " nil 0)
    ("bds" "\\begin{description}" nil 0)
    ("ben" "\\begin{enumerate}" nil 0)
    ("beq" "\\begin{equation}\\label{" nil 0)
    ("bfig" "\\begin{figure}" nil 0)
    ("bints" "\\bigcap" nil 0)
    ("bitm" "\\begin{itemize}" nil 0)
    ("blem" "\\begin{Lemma} " nil 0)
    ("bmpg" "\\begin{minipage}{\\textwidth}" nil 0)
    ("bnota" "\\notaestesa{GDV}{} " nil 0)
    ("bnote" "\\begin{Note} " nil 0)
    ("bpb" "\\begin{Problem} " nil 0)
    ("bprf" "\\begin{proof} " nil 1)
    ("bpro" "\\begin{proof} " nil 0)
    ("bprob" "\\begin{Problem} " nil 0)
    ("bprop" "\\begin{Proposition} " nil 0)
    ("bqst" "\\begin{Question} " nil 0)
    ("brmk" "\\begin{Remark} " nil 0)
    ("bthm" "\\begin{Theorem} " nil 0)
    ("bthmt" "\\begin{Theorem}[Gauss' Theorem] " nil 0)
    ("bvrb" "\\begin{verbatim}" nil 0)
    ("eqvt" "\\Leftrightarrow" nil 0)
    ("f12" "\\frac{1}{2}" nil 0)
    ("f13" "\\frac{1}{3}" nil 0)
    ("f14" "\\frac{1}{4}" nil 0)
    ("ftn" "\\footnote{}" nil 0)
    ("imp" "\\Rightarrow" nil 0)
    ("impb" "\\Leftarrow" nil 0)
    ("lel" "\\left\\langle" nil 0)
    ("lle" "\\langle" nil 0)
    ("lora" "\\longrightarrow" nil 0)
    ("lra" "\\leftrightarrow" nil 0)
    ("ngdv" "\\notaestesa{GDV}{" nil 0)
    ("ribr" "\\right\\}" nil 0)
    ("rir" "\\right\\rangle" nil 0)
    ("sct" "\\section{" nil 0)
    ("sns" "\\section*{" nil 0)
    ("sq" "^2" nil 0)
    ("ssn" "\\subsection{" nil 0)
    ("ssns" "\\subsection*{" nil 0)
    ("sube" "\\subseteq" nil 0)
    ("subs" "\\subset" nil 0)
    ("supe" "\\supseteq" nil 0)
    ("sups" "\\supset" nil 0)
    ("vbar" "\\mid" nil 0)
   ))
